<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Rutorika\\Sortable' => array($vendorDir . '/rutorika/sortable/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Lavary\\Menu\\' => array($vendorDir . '/lavary/laravel-menu/src'),
    'Laracasts\\Flash' => array($vendorDir . '/laracasts/flash/src'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
);
